package ies

import (
	"github.com/lvdund/asn1go/uper"
	"github.com/lvdund/rrc/utils"
)

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_msDot125 uper.Enumerated = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_msDot25  uper.Enumerated = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_msDot5   uper.Enumerated = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms1      uper.Enumerated = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms2      uper.Enumerated = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms4      uper.Enumerated = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms6      uper.Enumerated = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms8      uper.Enumerated = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms12     uper.Enumerated = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms16     uper.Enumerated = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms20     uper.Enumerated = 10
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms25     uper.Enumerated = 11
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms30     uper.Enumerated = 12
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms32     uper.Enumerated = 13
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms35     uper.Enumerated = 14
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms40     uper.Enumerated = 15
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms45     uper.Enumerated = 16
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17_Enum_ms50     uper.Enumerated = 17
)

type PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17 struct {
	Value uper.Enumerated `lb:0,ub:17,madatory`
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17) Encode(w *uper.UperWriter) error {
	var err error
	if err = w.WriteEnumerate(uint64(ie.Value), uper.Constraint{Lb: 0, Ub: 17}, false); err != nil {
		return utils.WrapError("Encode PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17", err)
	}
	return nil
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17) Decode(r *uper.UperReader) error {
	var err error
	var v uint64
	if v, err = r.ReadEnumerate(uper.Constraint{Lb: 0, Ub: 17}, false); err != nil {
		return utils.WrapError("Decode PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsN_r17", err)
	}
	ie.Value = uper.Enumerated(v)
	return nil
}
