package ies

import (
	"github.com/lvdund/asn1go/uper"
	"github.com/lvdund/rrc/utils"
)

const (
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms1    uper.Enumerated = 0
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms2    uper.Enumerated = 1
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms4    uper.Enumerated = 2
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms8    uper.Enumerated = 3
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms16   uper.Enumerated = 4
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms20   uper.Enumerated = 5
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms30   uper.Enumerated = 6
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms40   uper.Enumerated = 7
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms80   uper.Enumerated = 8
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms160  uper.Enumerated = 9
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms320  uper.Enumerated = 10
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms640  uper.Enumerated = 11
	PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17_Enum_ms1280 uper.Enumerated = 12
)

type PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17 struct {
	Value uper.Enumerated `lb:0,ub:12,madatory`
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17) Encode(w *uper.UperWriter) error {
	var err error
	if err = w.WriteEnumerate(uint64(ie.Value), uper.Constraint{Lb: 0, Ub: 12}, false); err != nil {
		return utils.WrapError("Encode PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17", err)
	}
	return nil
}

func (ie *PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17) Decode(r *uper.UperReader) error {
	var err error
	var v uint64
	if v, err = r.ReadEnumerate(uper.Constraint{Lb: 0, Ub: 12}, false); err != nil {
		return utils.WrapError("Decode PRS_ProcessingCapabilityOutsideMGinPPWperType_r17_ppw_durationOfPRS_Processing_r17_ppw_durationOfPRS_Processing1_r17_ppw_durationOfPRS_ProcessingSymbolsT_r17", err)
	}
	ie.Value = uper.Enumerated(v)
	return nil
}
